name: logidee_tools
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.0-134.5.beta <3.0.0'


dependencies:
  args: ^2.3.0
  path: ^1.8.1
  posix: ^5.0.0
  xml: ^6.4.2
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.20.1
