name: logidee_tools
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  args: ^2.4.2
  path: ^1.8.3
  posix: ^6.0.1
  xml: ^6.4.2
#   path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
